POST http://localhost:7071/api/EmployeesFn HTTP/1.1
content-type: application/json

{
    "_firstName": "Geralt",
    "_lastName": "Frostborn"
}

POST http://localhost:7071/api/EmployeesFn HTTP/1.1
content-type: application/json

{
    "_firstName": "Torin",
    "_lastName": "Moczybroda"
}

POST http://localhost:7071/api/EmployeesFn HTTP/1.1
content-type: application/json

{
    "_firstName": "Elara",
    "_lastName": "Ravenshadow"
}

GET http://localhost:7071/api/EmployeesFn/GetTime HTTP/1.1
content-type: application/json

{
    "Id": 2
}