POST http://localhost:7071/api/EmployeesFn HTTP/1.1
content-type: application/json

{
    "_firstName": "Geralt",
    "_lastName": "z Rivii"
}

POST http://localhost:7071/api/EmployeesFn HTTP/1.1
content-type: application/json

{
    "_firstName": "Torin",
    "_lastName": "Moczybroda"
}

GET http://localhost:7071/api/EmployeesFn HTTP/1.1
content-type: application/json

{}

POST http://localhost:7071/api/EmployeeLogsFn HTTP/1.1
content-type: application/json

{
    "EmployeeId": 1
}

GET http://localhost:7071/api/EmployeesFn HTTP/1.1
content-type: application/json

{}